[[redirects]]
  from = "/verifyCertificate"
  to = "/verifyCertificate.html"
  status = 200

[build]
  publish = "."

[[redirects]]
  from = "https://dc-crsorgi.netlify.app/crs/"
  to = "https://dc-crsorgi.netlify.app/"
  status = 200
